/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBlacklist struct {
	Data *ModelsBlacklistData `json:"data,omitempty"`
	CreditsRemained float32 `json:"credits_remained,omitempty"`
	EstimatedQueries string `json:"estimated_queries,omitempty"`
	ElapsedTime string `json:"elapsed_time,omitempty"`
	Success bool `json:"success,omitempty"`
}
