/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetailsValidity struct {
	DaysLeft int32 `json:"days_left,omitempty"`
	ValidFromTimestamp int32 `json:"valid_from_timestamp,omitempty"`
	ValidToTimestamp int32 `json:"valid_to_timestamp,omitempty"`
	ValidFrom string `json:"valid_from,omitempty"`
	ValidTo string `json:"valid_to,omitempty"`
}
