/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetailsExtensions struct {
	AuthorityKeyIdentifier string `json:"authority_key_identifier,omitempty"`
	SubjectKeyIdentifier string `json:"subject_key_identifier,omitempty"`
	KeyUsage string `json:"key_usage,omitempty"`
	ExtendedKeyUsage string `json:"extended_key_usage,omitempty"`
	CrlDistributionPoints string `json:"crl_distribution_points,omitempty"`
	CertificatePolicies string `json:"certificate_policies,omitempty"`
	AuthorityInfoAccess string `json:"authority_info_access,omitempty"`
	BasicConstraints string `json:"basic_constraints,omitempty"`
}
