/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBlacklistDataReportServer struct {
	Ip string `json:"ip,omitempty"`
	ReverseDns string `json:"reverse_dns,omitempty"`
	ContinentCode string `json:"continent_code,omitempty"`
	ContinentName string `json:"continent_name,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	CountryName string `json:"country_name,omitempty"`
	RegionName string `json:"region_name,omitempty"`
	CityName string `json:"city_name,omitempty"`
	Latitude float32 `json:"latitude,omitempty"`
	Longitude float32 `json:"longitude,omitempty"`
	Isp string `json:"isp,omitempty"`
}
