/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsAgeData struct {
	Host string `json:"host,omitempty"`
	DebugMessage string `json:"debug_message,omitempty"`
	DomainAgeFound bool `json:"domain_age_found,omitempty"`
	DomainRegistered string `json:"domain_registered,omitempty"`
	DomainCreationDate string `json:"domain_creation_date,omitempty"`
	DomainAgeInDays int32 `json:"domain_age_in_days,omitempty"`
	DomainAgeInMonths int32 `json:"domain_age_in_months,omitempty"`
	DomainAgeInYears int32 `json:"domain_age_in_years,omitempty"`
}
