/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBlacklistDataReportBlacklists struct {
	Engines *ModelsBlacklistDataReportBlacklistsEngines `json:"engines,omitempty"`
	Detections int32 `json:"detections,omitempty"`
	EnginesCount int32 `json:"engines_count,omitempty"`
	DetectionRate string `json:"detection_rate,omitempty"`
	Scantime string `json:"scantime,omitempty"`
}
