/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetails struct {
	Subject *ModelsSslDataCertificateDetailsSubject `json:"subject,omitempty"`
	Issuer *ModelsSslDataCertificateDetailsIssuer `json:"issuer,omitempty"`
	Signature *ModelsSslDataCertificateDetailsSignature `json:"signature,omitempty"`
	Validity *ModelsSslDataCertificateDetailsValidity `json:"validity,omitempty"`
	Extensions *ModelsSslDataCertificateDetailsExtensions `json:"extensions,omitempty"`
}
