/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificate struct {
	Found bool `json:"found,omitempty"`
	DebugMessage string `json:"debug_message,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
	Blacklisted bool `json:"blacklisted,omitempty"`
	ValidPeer bool `json:"valid_peer,omitempty"`
	DeprecatedIssuer bool `json:"deprecated_issuer,omitempty"`
	NameMatch bool `json:"name_match,omitempty"`
	Expired bool `json:"expired,omitempty"`
	Details *ModelsSslDataCertificateDetails `json:"details,omitempty"`
}
