/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsBlacklistDataReport struct {
	Host string `json:"host,omitempty"`
	DomainLength int32 `json:"domain_length,omitempty"`
	MostAbusedTld bool `json:"most_abused_tld,omitempty"`
	AlexaTop10k bool `json:"alexa_top_10k,omitempty"`
	AlexaTop100k bool `json:"alexa_top_100k,omitempty"`
	AlexaTop250k bool `json:"alexa_top_250k,omitempty"`
	Blacklists *ModelsBlacklistDataReportBlacklists `json:"blacklists,omitempty"`
	Category *ModelsBlacklistDataReportCategory `json:"category,omitempty"`
	Server *ModelsBlacklistDataReportServer `json:"server,omitempty"`
}
