/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslData struct {
	Certificate *ModelsSslDataCertificate `json:"certificate,omitempty"`
}
