/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetailsSignature struct {
	Serial string `json:"serial,omitempty"`
	SerialHex string `json:"serial_hex,omitempty"`
	Type_ string `json:"type,omitempty"`
}
