/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetailsSubject struct {
	Name string `json:"name,omitempty"`
	CommonName string `json:"common_name,omitempty"`
	AlternativeNames string `json:"alternative_names,omitempty"`
	OrganizationUnit string `json:"organization_unit,omitempty"`
	Organization string `json:"organization,omitempty"`
	Category string `json:"category,omitempty"`
	Country string `json:"country,omitempty"`
	Street string `json:"street,omitempty"`
	PostalCode string `json:"postal_code,omitempty"`
	State string `json:"state,omitempty"`
	Location string `json:"location,omitempty"`
}
