/*
 * apivoid
 *
 * apivoids client for sendpost
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsSslDataCertificateDetailsIssuer struct {
	CommonName string `json:"common_name,omitempty"`
	Organization string `json:"organization,omitempty"`
	Country string `json:"country,omitempty"`
	State string `json:"state,omitempty"`
	Location string `json:"location,omitempty"`
	OrganizationUnit string `json:"organization_unit,omitempty"`
}
